name: publish to nuget
on:
  push:
    branches:
      - publish # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]   
    steps:      
      - uses: actions/checkout@v2
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          include-prerelease: true
      # You can test your matrix by printing the current dotnet version
      - name: Build
        # build dotnet with output ./build.zip
        run: dotnet pack  -o ./pack 
        # Runs the specified script
        #echo pwd
      - name: Run a multi-line script
        run: |
          dotnet nuget push "./pack/AiWrappers.0.0.1.nupkg" --api-key ${{ secrets.AIWRAPPERS }} --source https://api.nuget.org/v3/index.json


      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      